services:
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "4200:80"
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local